### ISSUE TITLE
Visual Studio subscription  as a membership benefit

### ISSUE THREAD

**Issue by ENikS** [dotnet-foundation/wg-membership#13]
## Visual Studio (former MSDN) subscription as a benefit

I would like to propose implementing "Visual Studio subscription" as a membership benefit.

## Aims / Benefits

We, as a whole foundation could easily qualify for volume licensing and perhaps with negotiated discount it could be even free to certain membership levels.

The payment could be an opt in option or just integral part of membership fee.

I think it is quite obvious that access to latest tools and technologies is essential for members to continue good work they are doing in promoting the platform and technology.

**Comment by mrlacey** [comment]
For clarification:
- Do you mean [Visual Studio subscriptions](https://visualstudio.microsoft.com/subscriptions/)? (MSDN subscriptions were renamed in 2020 but that was before this issue was opened so just want to make sure everyone is talking about the same thing.)
- What benefits are you particularly interested in? (Based on the current cost of a VS subscription, even very generous volume licensing terms will not get anywhere close to the recommended voluntary foundation donation amount, but that doesn't that all benefits are out. Knowing the specific things that you think would most benefit foundation members may help make a case for specifics--rather than a desire to "give us everything.") Do you want tools or services? Credit for or access to subscription services? support? training? Something else? Be specific.

**Comment by clairernovotny** [comment]
For Visual Studio, there's the Community Edition that's already free. What else would you be looking for?

**Comment by ENikS** [comment]
Community Edition is missing essential tool: 'Code Coverage' tool for test cases. 

It is invaluable for quality development that .NET Foundation projects should strive for. When I started to use it on [Unity](https://github.com/unitycontainer) project I discovered more than 50 new bugs and issues that were hiding in code. Now I can't imagine doing any serious work without it.

**Comment by clairernovotny** [comment]
Unfortunately, giving VS Pro away to members is far beyond what the Foundation can do, especially given Community exists. For code coverage, there are other free tools, like [Coverlet](https://github.com/coverlet-coverage/coverlet) (which is also a .NET Foundation project). I use that in many of my projects. There are Add-ins for VS and VSfM too: https://github.com/coverlet-coverage/coverlet#Visual-Studio-Add-In.

**Comment by ENikS** [comment]
I am not proposing to ask for handouts. 

With so many members and developers we should be able to qualify for a volume licensing without requiring any special treatment from Microsoft.

**Comment by clairernovotny** [comment]
Volume licensing has minimum purchase requirements that are quite high. You might be better off going through a reseller.

**Comment by ENikS** [comment]
> Software
> If your maintainers need access to certain software to enable them to work more effectively on their open source projects, contact us and we can talk with vendors on your behalf. Microsoft has sponsored a number of MSDN subscriptions for .NET Foundation project contributors over the past 12 months.

This is from [.NET Foundation](https://dotnetfoundation.org/projects/why-join) page. I think it would be nice if the foundation can actually deliver on the promise.

I'd like the foundation to at least make an attempt. If Microsoft said NO, we would know: Ah, we are too few, so many more members have to join to qualify... 

Saying 'it can't be done' without even trying, kind of breaks the spirit of the whole thing. ... and creates false advertisement in the process.

**Comment by BillWagner** [comment]
@ENikS 

>I am not proposing to ask for handouts.

> With so many members and developers we should be able to qualify for a volume licensing without requiring any special treatment from Microsoft.

I understand what you'd like, and it sounds reasonable. Unfortunately, the math doesn't work out.  Remember that the foundation asks for (but does not require) $100 USD per year. Even if we did qualify for Enterprise discounts (@clairernovotny has already commented on that), the price to the foundation would be higher than the membership dues. That would leave us with three bad alternatives:

- *Raise membership dues, including making them mandatory*: We're rejecting that because we want to grow membership, especially in underserved regions and communities where $100 USD is already a burden.
- *Provide a small discount, rather than a free benefit*: The math dictates that "small discount" really isn't a benefit.
- *Stop spending foundation money on anything else*: We want to support project and members in many other ways. This one isn't sustainable.

We are actively looking at benefits for members, and how we can do more. This isn't practical for the entire membership.

**Comment by BillWagner** [comment]
Regarding the website on MSDN subscriptions for projects:

I will need to verify, but I don't think the foundation has done that recently. (The change from Visual Studio subscription to MSDN subscription makes me think it's a stale page.)

Thank you @ENikS for pointing this out. We should update that. 

It's true that cost is a part of that. It's also that we want to continue to update the services we provide to projects. More and more, we're getting requests for other services from project maintainers.

**Comment by ENikS** [comment]
> Provide a small discount ...

Sounds good. For developers like me, who spend own money on supporting projects every bit helps.

As I said above, the foundation [already advertises](https://dotnetfoundation.org/projects/why-join) this as a benefit to its members. It has to at least try to deliver.

**Comment by ENikS** [comment]
With volume licensing there are no cost for the foundation. Members will be paying their own share. The only thing that is required of the foundation is to negotiate sales terms and provide means for members to pay for the subscription.

**Comment by mrlacey** [comment]
> As I said above, the foundation [already advertises](https://dotnetfoundation.org/projects/why-join) this as a benefit to its members. It has to at least try to deliver.

As per your link, MSDN subscriptions are listed as a possible benefit for **projects** that are part of the foundation, not individual members.

**Comment by ENikS** [comment]
I personally would be fine with either.

**Comment by ENikS** [comment]
To resolve this dispute I would like to propose a small referendum. 

Ask members in next foundation newsletter to comment on this issue and see how much interest is there for this benefit.

If no sufficient interest is expressed, we can safely close this whole thing.

**Comment by clairernovotny** [comment]
We have a limited number of MSDN subscriptions for projects, based on need. It's just not something we can offer members at large tab this time.

**Comment by ENikS** [comment]
@clairernovotny 

You do realize that:

> We have a limited number of MSDN subscriptions for projects, based on need. It's just not something we can offer members at large tab this time.

and [this](https://dotnetfoundation.org/projects/why-join) are bait and switch (illegal in every state of US).

You are saying: Come, join, sign your IP to the foundation and we will take care of you. Once you join and become member, here, in a quiet corner of issues tracker you are informed that only **special** projects are helped. 

The decision is based on some opaque criteria that no one bothered to list and does not correspond with the actual state of the project asking for help. 

Again, I am not proposing charitable contributions from the foundation. Volume licensing is self sustainable and in the spirit of collective and open OSS foundation. It supposed to help all authors with development, not just select few, as clearly stated on the site.

**Comment by clairernovotny** [comment]
I'm going to close this issue now as it's not productive. There are other, better, options for buying Visual Studio if that's what's desired. We are not software resellers. We absolutely do have VS subscriptions for member project, however due to the limited number, it is need based. Free options, such as VS Community with the aforementioned coverage tool, appear to fulfill the stated need.
