### ISSUE TITLE
Budget Proposals

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#28]
## Brief Summary of idea

Given we get £10 - 15K funding, what should be be spending this budget on and why?

## Aims / Benefits

To give us a prioritised list of focuses for this budget.

## Requirements

Please post in comments ideas for what you think we should spend this budget on and up-vote peoples ideas using the 👍🏼  reaction on the comment.

**Comment by BillWagner** [comment]
Answering a question from twitter:

The purpose of this budget is to set the plans for what the membership committee spends *to benefit existing and new members* of the .NET Foundation.

**Comment by khalidabuhakmeh** [comment]
Membership benefits that I could see spending a  £10 - 15K budget include, but are not limited to the following. The .NET Foundation would have to implement any suggestions in a lottery system where random members could win. The lottery is due to limited funds.

## Swag 

Members would get the opportunity to pick swag from the .NET Foundation store or a partner projects apparel store. Currently, the .NET Foundation sells .NET-themed shirts, stickers, and more.

## Subscriptions

Members would get a yearly subscription to an approved online service or licensed software. 

## Charity

Give individual members a chance to select a charity/group to donate a sum of money ($100, for example), with an opportunity to write a blog post about why they feel the group is deserving of funds and why others should take notice.

## Hour With An Expert

Members would get an opportunity to get an office hour with an individual of particular expertise to either talk or help solve an existing problem. The foundation would pay the expert for their hour.

## Gift A Membership

Folks get the opportunity to gift a membership to an individual, which the foundation pays for through the budget. **This is not a free membership.**.

**Comment by wordshaker** [comment]
> ## Gift A Membership
> Folks get the opportunity to gift a membership to an individual, which the foundation pays for through the budget. **This is not a free membership.**.

Is there a way I could "donate" a membership? If I wanted to pay for the membership for someone from an under-represented group? Once the value/benefits of membership are clearer, this is something I would be interested in doing.

> ## Hour With An Expert
> Members would get an opportunity to get an office hour with an individual of particular expertise to either talk or help solve an existing problem. The foundation would pay the expert for their hour.

I like this. 

As an event organiser as well - if there was any means of the .NET Foundation providing travel & expenses or a small amount of money / help to getting Keynote speakers that would be a big boon. I run a not-for-profit conference on a very limited budget, and experienced/crowd drawing Keynote speakers can be hard to find and costly.
