### ISSUE TITLE
Survey different types of member needs

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#6]
## Brief Summary of idea

There are many different means to work in .NET including work in and around:
- Unity
- Blazor
- F#
- C#

It would be good to get information on how we can include the different areas of the .NET community and what benefits they would seek from the .NET Foundation.

## Aims / Benefits

- Ensures that all aspects of .NET are included in the community
- Maintain and increase membership

## Requirements

Would need a way to reach out to these communities and meaningfully aggregate the feedback into something workable

**Comment by BillWagner** [comment]
The purpose is to learn from our membership what benefits would be useful to them. We've discussed in our meeting that the membership committee has self-selected as one type of member.

**Comment by BillWagner** [comment]
Notes during our meeting on Jan 5:

Some of these questions may have already been asked and answered on the [survey that was started during .NET Conf](https://dotnetfoundation.org/about/survey).

- We should make the survey public to get as much information as possible from "the entire community" instead of "current members". We want to learn what would encourage them to join the foundation and contribute.
- Include open questions on "What should the foundation do?" "What would you do as a member of the foundation?" "What part of the work would make you want to join?"
  - What kind of work should the foundation support to encourage you to join? 
- What other technical stacks or communities do you admire? What about those do you admire that the .NET foundation should adopt?
- (Similar) How do you identify yourself as a ".NET developer", "C# developer", "F# developer", "VB.NET", "ASP.NET Core" etc?
- Have you started an OSS project? Why or why not? What are the hurdles?
- How do you contribute? (e.g. twitch, blogs, project contributions, meetup speaker/organizer, etc)?
  - What activities do you think should count as a contributing?
- Learn more about their thoughts on gamification (See #5)
- What's preventing you from joining today?
- How to get the word out (probably already solved by Beth and Deedee).
- Are you a beginner, intermediate, "highly skilled", etc?

**Comment by BillWagner** [comment]
Most or all of the questions above are part of the current [state of .NET survey](https://dotnetfoundation.org/about/survey). We'll get those results when the survey closes, so I think this issue can be closed for our purposes.

Thoughts @wordshaker ?

**Comment by wordshaker** [comment]
I'm happy to have this closed. Can you send me a link to share the survey now that it's opened up? Would be good to have a point in the meeting that follows the closing date of the survey to create actions points off the information as well if possible.

**Comment by BillWagner** [comment]
Closing per discussion.

@wordshaker The link to the survey is in my previous comment.
